[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
build_src_flags = -O0
build_flags =
    -Wl,--defsym=__heap_size=0x50000
    -DCFG_TUD_ENABLED=0
    -DCFG_TUH_ENABLED=1
    -DCFG_TUH_HID=4
    -DCFG_TUSB_RHPORT0_MODE=2
    -DCFG_TUSB_DEBUG=0
    -I src
    -I lib/tinyusb/src
    -I lib/tinyusb/hw
lib_deps =
    tinyusb
lib_ldf_mode = chain+
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
